theme: jekyll-theme-slate
hostname: vote.mitros.org
project_title: Committee to Elect Piotr Mitros
project_tagline: "Bringing excellence in education to the public schools of Cambridge"
title: Committee to Elect Piotr Mitros
description: For excellence in the Cambridge Public School District